# Generated by Django 4.2.17 on 2024-12-13 06:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_remove_quizsession_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='correct_choice',
            new_name='correct_option',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_d',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='user_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='option_a',
            field=models.CharField(default='Default Option', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.CharField(default='Default Option', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.CharField(default='Default Option', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(default='Default Option', max_length=255),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='incorrect_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
